#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1

# Start SXHKD for keybinds
sxhkd &

# Monitor Config
bspc monitor -d www dev sys cht mus msc

# Border Config
bspc config border_width         3

# Window Gap & Padding Config
bspc config top_padding          32
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config window_gap           12

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Color Config
bspc config normal_border_color  '#222222'
bspc config active_border_color  '#FF79C6'
bspc config focused_border_color  '#9112ed'
bspc config presel_feedback_color  '#FF79C6'

# Don't tile
bspc rule -a feh state=floating

# Tile
bspc rule -a emacs state=tiling

# Defaults
bspc rule -a Discord desktop=^4

