#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1

# Start SXHKD for keybinds
sxhkd &

# Monitor Config
if test -f $XDG_CONFIG_HOME/laptop; then
  bspc monitor -d ww1 ww2 dv1 dv2 dv3 sys ct1 ct2 mus msc
else
  bspc monitor DisplayPort-0 -d dv1 dv2 dv3 sys ct1
  bspc monitor HDMI-A-0 -d ww1 ww2 ct2 mus msc
fi

# Border Config
bspc config border_width         2

# Window Gap & Padding Config
bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config window_gap           0

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Color Config
bspc config normal_border_color  '#5c6370'
bspc config active_border_color  '#9c71c7'
bspc config focused_border_color  '#9c71c7'
bspc config presel_feedback_color  '#e5c07b'

# Don't tile
bspc rule -a feh state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Chromium:crx_baipgmmeifmofkcilhccccoipmjccehn state=floating
bspc rule -a 'Microsoft Teams - Preview' state=floating

# Defaults
bspc rule -a Chromium desktop=ww1
bspc rule -a discord desktop=ct1
bspc rule -a 'Microsoft Teams - Preview' desktop=ct2
bspc rule -a Chromium:crx_baipgmmeifmofkcilhccccoipmjccehn desktop=ct2
bspc rule -a jetbrains-datagrip desktop=dv3
bspc rule -a ktranger desktop=msc
bspc rule -a Spotify:spotify desktop=mus

# Polybar
pb &

